apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: prod-core-team
  description: Productization Core team
spec:
  type: team
  profile:
    displayName: Prod Core team
    email: prod-core@redhat.com
  parent: application-services
  children: [pnc-team]
